### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by gandie** [evunexx/ffs#1]
I noticed you have some files in your repository which are not needed for the actual project. You may remove it from git repo to keep it small and clear.

While removing it may be a good idea to add a `.gitignore` file in the process. Check out [this example](https://github.com/gandie/Ants/blob/master/.gitignore) to find what to write into this file.

Files which may vanish:
+ `.vscode` folder keeping project settings for your editor
+ `__pycache__` folder contains byte-code built during runtime by the python interpreter
+ `flask-env` Python environment won't work on other system than yours:

```bash
~/D/P/ffs (master|✔) $ . flask-env/bin/activate.fish 
set: Warning: $PATH entry "/home/sebastian/Schreibtisch/ffs/flask-env/bin" is not valid (No such file or directory)
``` 

I suggest you replace `flask-env` folder with:
+ `requirements.txt` file containing your python dependencies, this may be created via:
 `pip freeze > requirements.txt`
+ i suggest to remove the version-pinning done by `pip freeze` by removing the `==VERSION` from `requirements.txt` after creating
+ Check [this example](https://github.com/gandie/NXT/blob/master/requirements.txt) for notation with version and without
+ and a short guide in `README` telling me how to build the environment something like:
```
virtualenv -p python3 flask-env
. flask-env/bin/activate
pip install -r requirements.txt
```

**Comment by evunexx** [comment]
thanks for the detailed notification ! Fixed it
